import {
  PiggyBank,
  Wallet,
  Target,
  House,
  Car,
  Plane,
  GraduationCap,
  Gamepad2,
  Smartphone,
  Laptop,
  Heart,
  Dumbbell,
  Briefcase,
  Rocket,
  ShoppingCart,
  Gift,
  PartyPopper,
  Trophy,
  Headphones,
  Music,
  MonitorPlay,
  Disc3,
  Camera,
  Tablet,
  Book,
  Calculator,
  Apple,
  Goal,
  Star,
  Mountain,
} from "lucide-react";

export const iconos = {
  "piggy-bank": PiggyBank,
  wallet: Wallet,
  target: Target,
  house: House,
  car: Car,
  plane: Plane,
  "graduation-cap": GraduationCap,
  gamepad2: Gamepad2,
  smarthphone: Smartphone,
  laptop: Laptop,
  heart: Heart,
  "dumb-bell": Dumbbell,
  "brief-case": Briefcase,
  rocket: Rocket,
  "shoping-cart": ShoppingCart,
  gift: Gift,
  music: Music,
  headphones: Headphones,
  "monitor-play": MonitorPlay,
  "party-popper": PartyPopper,
  disc3: Disc3,
  camera: Camera,
  tablet: Tablet,
  book: Book,
  calculator: Calculator,
  apple: Apple,
  goal: Goal,
  star: Star,
  trophy: Trophy,
  mountain: Mountain,
} as const;
export type IconosType = keyof typeof iconos;
